dist: trusty
language: java
sudo: required

jdk:
  - openjdk8

before_install:
  - sudo apt-get install jq
  - wget -O ~/codacy-coverage-reporter-assembly-latest.jar https://github.com/codacy/codacy-coverage-reporter/releases/download/6.0.0/codacy-coverage-reporter-6.0.0-assembly.jar
  
install:
  - cd desapp-groupF-backend/ && mvn clean install -Dmaven.compiler.target=1.8 -Dmaven.compiler.source=1.8
  
script:
  - mvn test -B
  
after_success:
  - bash <(curl -Ls https://coverage.codacy.com/get.sh) report -l Kotlin --force-language 
  - java -jar ~/codacy-coverage-reporter-assembly-latest.jar report -l Java -r target/site/jacoco/jacoco.xml

deploy:
  provider: heroku
  skip_cleanup: true
  api_key: $HEROKU_KEY_API
  app: buyfromhome