dist: trusty
language: java
sudo: required

jdk:
  - openjdk8

install:
  - cd desapp-groupF-backend/ && mvn clean install -Dmaven.compiler.target=1.8 -Dmaven.compiler.source=1.8
  
script:
  - mvn test -B
  
after_success:
  - mvn cobertura:cobertura
  - bash <(curl -Ls https://coverage.codacy.com/get.sh) report -l Java -r target/site/cobertura/coverage.xml --partial -DprojectToken=$CODACY_PROJECT_TOKEN